apiVersion: v1
kind: Service
metadata:
  name: {{ include "tetris.fullname" . }}
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "tetris.name" . }}
